name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: siamatic/smtrack-monitor:1.0.0
    steps:
    - uses: actions/checkout@v4
    - name: Login to docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE_NAME }}
    - name: Send success message to slack
      id: slack
      uses: slackapi/slack-github-action@v1.27.0
      with:
        payload: |
          {
            "text": "GitHub Action build ${{ env.IMAGE_NAME }} result: ${{ job.status }} 🖕🖕🖕🖕",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "GitHub Action build ${{ env.IMAGE_NAME }} result: ${{ job.status }} 🖕🖕🖕🖕"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK